// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _g_palette_H_
#define _g_palette_H_

#include <types.h>

extern const u8 g_palette[16];

#endif
