// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _tileset_palette_H_
#define _tileset_palette_H_

#include <types.h>

extern const u8 tileset_palette[15];

#endif
