;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: soundtrack/ingame.aks
;;;; Generation time: mié oct 31 21:27:43 CET 2018
;;;;

;;;; Song 'ingame_theme' metadata constants
ingame_theme_address = 0xBF2
ingame_theme_size    = 1089
ingame_theme_end     = 0x1032

;;;; Song 'ingame_theme' declaration
.globl _ingame_theme
