;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: soundtrack/mainmenu.aks
;;;; Generation time: mié oct 31 21:27:44 CET 2018
;;;;

;;;; Song 'main_menu_theme' metadata constants
main_menu_theme_address = 0x592
main_menu_theme_size    = 1631
main_menu_theme_end     = 0xbf0

;;;; Song 'main_menu_theme' declaration
.globl _main_menu_theme
