;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: soundtrack/SFX.aks
;;;; Generation time: mié oct 31 21:27:43 CET 2018
;;;;

;;;; Song 'sound_effects' metadata constants
sound_effects_address = 0x1034
sound_effects_size    = 180
sound_effects_end     = 0x10e7

;;;; Song 'sound_effects' declaration
.globl _sound_effects
